### ISSUE TITLE
Add support for http_proxy variable

### ISSUE THREAD

**Issue by leepowelldev** [applitools/eyes-storybook#16]
Trying to run for the first time and receiving the following error:

```
Using @applitools/eyes-storybook version 2.6.18.

✔ Storybook was started
✔ Reading stories
⠼ Done 69 stories out of 70(node:19985) UnhandledPromiseRejectionWarning: TypeError: testResults.every is not a function
    at didTestPass (/Users/8888/Sites/Company/App/node_modules/@applitools/eyes-storybook/src/renderStories.js:44:26)
    at Array.every (<anonymous>)
    at renderStoriesPromise.then.results (/Users/8888/Sites/Company/App/node_modules/@applitools/eyes-storybook/src/renderStories.js:39:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:19985) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 141)
(node:19985) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠴ Done 70 stories out of 70

The following errors were found:
Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Error: write EPROTO 4557878720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:


Important notice: the Applitools visual tests are currently running with a concurrency value of 10.
This means that only up to 10 visual tests can run in parallel, and therefore the execution might be slow. This is the default behavior for free accounts.
If your account does support a higher level of concurrency, it's possible to pass a different value by specifying `concurrency:X` in the applitools.config.js file.
For more information on how to configure the concurrency level, visit the following link: https://www.npmjs.com/package/@applitools/eyes-storybook#concurrency.
If you are interested in speeding up your visual tests, contact sdr@applitools.com to get a trial account and a higher level of concurrency.
```

**Comment by danielschwartz85** [comment]
Hi Tnx for the issue, and sorry for the late response.
Can u share the @applitools/visual-grid-client version ? 
```npm ls --depth=0```

Also would help if u can share logs of this run by:
1. adding ```APPLITOOLS_SHOW_LOGS=true``` env variable
2. Or adding showLogs: true to ```applitools.config.js```

**Comment by leepowelldev** [comment]
Hi - sorry for the delay, it's `12.8.4` Thanks. Happy to send logs to you - have you got an email address I can use as they're quite large.

**Comment by danielschwartz85** [comment]
I'd rather not share it here, can u upload it to google drive and share a link ?

**Comment by leepowelldev** [comment]
Yep will do - in the meantime, looking at the logs, I think it might be something to do with our proxy. Does `eyes-storybook` respect system wide http_proxy settings?

**Comment by danielschwartz85** [comment]
@leepowellcouk what do u mean by _respect_ system wide http_proxy ?
We fetch resources from puppeteer (while SB is opened) and also fetch resources in the node process u run (eyes-storybook cmd).

**Comment by leepowelldev** [comment]
I'm seeing errors fetching assets in the log:
```
2019-05-24T10:50:43Z Eyes: [LOG    ] {} Page.<init>(): JSHandle:console.groupEnd
2019-05-24T10:50:43Z Eyes: [LOG    ] {} Page.<init>(): JSHandle:message arrived at preview JSHandle:storybooks/knobs/set JSHandle@object
2019-05-24T10:50:43Z Eyes: [LOG    ] {} Page.<init>(): JSHandle:message arrived at preview JSHandle:storybook/a11y/result JSHandle@object
2019-05-24T10:50:43Z Eyes: [LOG    ] {} Page.<init>(): JSHandle:[dom-snapshot] error while fetching JSHandle:http://cdn.aviva.com/static/core/v.4.8.0/css/vendor/normalize/normalize.css JSHandle@error
2019-05-24T10:50:43Z Eyes: [LOG    ] {} Page.<init>(): JSHandle:[dom-snapshot] error while fetching JSHandle:http://cdn.aviva.com/static/core/v.4.8.0/css/customer/core-split1.css JSHandle@error
2019-05-24T10:50:43Z Eyes: [LOG    ] {} Page.<init>(): JSHandle:[dom-snapshot] error while fetching JSHandle:http://cdn.aviva.com/static/core/v.4.8.0/css/customer/core-split.css JSHandle@error
2019-05-24T10:50:43Z Eyes: [LOG    ] {} Page.<init>(): JSHandle:[dom-snapshot] error while fetching JSHandle:http://cdn.aviva.com/static/core/v.4.8.0/css/customer/core-split2.css JSHandle@error
2019-05-24T10:50:43Z Eyes: [LOG    ] {} Page.<init>(): JSHandle:[dom-snapshot] error while fetching JSHandle:http://cdn.aviva.com/static/core/v.4.8.0/css/customer/forms-extended-a.css JSHandle@error
2019-05-24T10:50:43Z Eyes: [LOG    ] {} Page.<init>(): JSHandle:[dom-snapshot] error while fetching JSHandle:http://cdn.aviva.com/static/core/v.4.8.0/css/customer/forms-extended-b.css JSHandle@error
```
We're running this behind a proxy, and running Storybook directly doesn't have this issue as I believe it uses the `http_proxy` environment variable for it's requests - so I was wondering if this tool does the same.

**Comment by danielschwartz85** [comment]
u can set 
```proxy: 'https://myproxy'```
in ```applitools.config.js``` or use ```APPLITOOLS_PROXY=https://myproxy```
(we need to consider reading proxy_url nevertheless.. will update here..)

**Comment by danielschwartz85** [comment]
@leepowellcouk does this solve the issue ? can I close ?

**Comment by danielschwartz85** [comment]
will update regarding the http_proxy env variable support.

**Comment by leepowelldev** [comment]
Sorry, not had a change to look at this yet - will try in the next couple of days.

**Comment by danielschwartz85** [comment]
> will update regarding the http_proxy env variable support.

Note: we do support HTTP_PROXY & HTTPS_PROXY env variables..

**Comment by danielschwartz85** [comment]
For anyone else looking into proxy issues see: https://github.com/applitools/eyes-storybook#advanced-configuration

**Comment by danielschwartz85** [comment]
If anything else is needed feel free to re-open.
