### ISSUE TITLE
Error: Evaluation failed: [object Object]

### ISSUE THREAD

**Issue by Corinos** [applitools/eyes-storybook#21]
I'm pretty new to this stuff, but I added applitools-eyes to a package my team is using with storybook, and when I try to run it, I don't get very far:
```
Using @applitools/eyes-storybook version 2.7.21.

2019-08-01T18:19:56Z Eyes: [LOG    ] {} (): Running with the following config:
concurrency           : 60
storybookPort         : 9000
storybookHost         : localhost
storybookConfigDir    : .storybook
storybookUrl          : http://url-of-my-app.com
storybookStaticDir    : undefined
showStorybookOutput   : false
waitBeforeScreenshots : 700
tapFilePath           : undefined
exitcode              : true
appName               : Project
showLogs              : true
apiKey                : MyApIKeyHere
matchLevel            : Layout2
batchName             : Testing
agentId               : eyes-storybook/2.7.21

2019-08-01T18:19:56Z Eyes: [LOG    ] {} (): eyesStorybook started
2019-08-01T18:19:56Z Eyes: [LOG    ] {} (): browser launched
2019-08-01T18:19:56Z Eyes: [LOG    ] {} (): 3 pages open
2019-08-01T18:19:56Z Eyes: [LOG    ] {} (): got script for processPage
2019-08-01T18:19:56Z Eyes: [LOG    ] {} (): finished creating functions
⠋ Reading stories2019-08-01T18:19:56Z Eyes: [LOG    ] {} (): navigating to storybook url: http://url-of-my-app.com
⠦ Reading stories2019-08-01T18:20:00Z Eyes: [LOG    ] {} (): Getting stories from storybook
⠏ Reading stories2019-08-01T18:20:10Z Eyes: [LOG    ] {} (): Error: Evaluation failed: [object Object]
    at ExecutionContext._evaluateInternal (/Users/me/project/node_modules/puppeteer/lib/ExecutionContext.js:122:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/me/project/node_modules/puppeteer/lib/helper.js:111:15)
    at DOMWorld.evaluate (/Users/me/project/node_modules/puppeteer/lib/DOMWorld.js:112:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  -- ASYNC --
    at Frame.<anonymous> (/Users/me/project/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.evaluate (/Users/me/project/node_modules/puppeteer/lib/Page.js:827:43)
    at Page.<anonymous> (/Users/me/project/node_modules/puppeteer/lib/helper.js:112:23)
    at eyesStorybook (/Users/me/project/node_modules/@applitools/eyes-storybook/src/eyesStorybook.js:67:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
2019-08-01T18:20:10Z Eyes: [LOG    ] {} (): total time:  
⠋ Reading stories
Test is finished but no results returned.

✨  Done in 14.71s.
```
I haven't made any changes to puppeteer, so I'm not sure what this could be related to.

**Comment by danielschwartz85** [comment]
Hi @Corinos,
I see that you started eyes-storybook with a storybook url of: ```http://url-of-my-app.com```
is your storybook served from this url (via proxy etc,,) ? 
1. If no then set [storybookUrl](https://github.com/applitools/eyes-storybook#advanced-configuration) according to your needs (i.e. remove the parameter for a local storybook run or set another url to where your storybook is served from).
2. If yes then can you supply the logs of the run ? do this by adding ```showLogs: true``` to applitools.config.js or by adding ```export APPLITOOLS_SHOW_LOGS=true``` env variable to your run.

Also can you update your package and see if this error occurs ? (or if a more verbose error is shown)
```npm update @applitools/eyes-storybook```
 Tnx.

**Comment by Corinos** [comment]
Hey, thanks for the response. That url was just a placeholder. I was using
my real url. The section that I have in the issue is the whole log, I
believe. Logs were on. I'll update my package and see how it goes.

**Comment by danielschwartz85** [comment]
@Corinos as far as I see eyes-storybook tried to load ```http://url-of-my-app.com``` as the storybook url, perhaps the placeholder was not populated..

**Comment by Corinos** [comment]
I altered the url in the log before sending it. Do you think this error
could happen because of my actual url?

**Comment by danielschwartz85** [comment]
Ho I see, then no reason to think the url is to blame.. sorry.
please update if the version update reveals new info.

**Comment by Corinos** [comment]
I need to shelf this for a day or two.  I'll close it and create a new one if updating my package doesn't do the job.  Thanks for the help @danielschwartz85
